name: smarkiapp2
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl_phone_field: ^3.2.0
  flutter_native_splash: ^2.4.4
  syncfusion_flutter_sliders: ^28.2.5
  flag: ^7.0.0
  firebase_core: ^3.12.0
  firebase_auth: ^5.5.0
  cloud_firestore: ^5.6.5
  shared_preferences: ^2.5.2
  get: ^4.7.2
  mobile_scanner: ^6.0.7
  wheel_picker: ^0.2.1
  youtube_player_iframe: ^5.2.1
  flutter_inappwebview: ^6.0.0-beta.25

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
